### ISSUE TITLE
Error in Subprocess on Create/Withdrawal Data

### ISSUE THREAD

**Issue by n6a1t4e** [GlacierProtocol/glacierprotocol.github.io#45]
Hey everyone, I'm pretty sure this is a personal problem and not an issue with Glacier, but I can't find any solutions online.  I get this error whenever I try to run create-deposit-data or create-withdrawal data.  Any suggestions?

Traceback (most recent call last):
  File "./glacierscript.py", line 871, in <module>
    deposit_interactive(args.m, args.n, args.dice, args.rng)
  File "./glacierscript.py", line 635, in deposit_interactive
    ensure_bitcoind_running()
  File "./glacierscript.py", line 311, in ensure_bitcoind_running
    bitcoind_call("-daemon", "-connect=0.0.0.0")
  File "./glacierscript.py", line 143, in bitcoind_call
    _, retcode, _ = run_subprocess("bitcoind", *args)
  File "./glacierscript.py", line 108, in run_subprocess
    pipe = subprocess.Popen(cmd_list, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=1)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by bitcoinhodler** [comment]
GlacierScript is only intended to run on an Ubuntu live system on the quarantined laptops. It expects to have Bitcoin Core installed, which the protocol doc takes care of.

It looks like you're trying to run it on Windows, which I've never tried and likely won't work, and it's failing because it can't find `bitcoind`, the Bitcoin Core executable.

Perhaps if you had `bitcoind.exe` in your `PATH` it would make progress...but I still wouldn't expect it to work. It runs other programs like `zbarimg` and `qrencode` that also won't be there on a Windows system.

I hope you're only playing around to investigate if Glacier is right for you. If you're not following the full process (with quarantined laptops running Ubuntu live) then you're not getting the full security of Glacier, and there are far better wallet systems out there if you're not seeking the full security of Glacier.

If you just want to play around, download VirtualBox and boot an Ubuntu Live ISO.  Install packages `qrencode`, `zbartools`, and download & install Bitcoin Core. Then you should be able to run GlacierScript.

**Comment by n6a1t4e** [comment]
Thanks for the response @bitcoinhodler ! Yes, I was just testing out Glacier, seeing the different ways to experiment with generating multi-sig keys.  I'll see if I get anywhere by adding `bitcoind` to my path, and maybe in the future I will test with quarantined laptops. Again, thanks for your help!
